mailcow/mailcow

- includes/functions.sh
- nginx/conf/sites-available/mail
OpenSSL sollte Zertifikate nur noch mit SHA2 erstellen, da SHA1 als unsicher angesehen wird.
Außerdem haben einige Browserhersteller angekündigt, künftig keine SHA1 Zertifikate mehr zu akzeptieren. 
(http://googleonlinesecurity.blogspot.de/2014/09/gradually-sunsetting-sha-1.html)
Auch sollte nginx die SSL-Session Cachen, um die Server-CPU nicht unnötig durch wiederholte SSL-Handshakes zu beschäftigen. 
Die 5MB Cache sollten für ca. 5.000 Verbindungen reichen
> Use SHA2 instead of SHA1

- nginx/conf/htdocs/fcc/inc/functions.inc.php
In PHP sollte mysqli_* statt mysql_* genutzt werden, da das alte mysql_* in einer zukünftigen Version entfernt werden wird.
Quelle:
http://php.net/manual/de/faq.databases.php#faq.databases.mysql.deprecated
> Use mysqli_* instead of mysql_*

- fail2ban/conf/jail.d/dovecot.conf
- fail2ban/conf/jail.d/postfix-sasl.conf
- fail2ban/conf/jail.d/postfix.conf
- fail2ban/conf/jail.d/sieve.conf
- fail2ban/conf/jail.d/sshd.conf
- fail2ban/conf/jail.local
- includes/functions.sh
- spamassassin/conf/spamlearn
roundcube: using the update tool of roundcube saves user changes, so y not use it?
fail2ban: to keep user changes moving default config to jail.d/*.conf and on update, restore *.local
spamassassin: check if there are emails to learn, otherwise do nothing
> Try to keep user configuration on update

- webserver/htdocs/mail/do.php
- webserver/htdocs/mail/inc/functions.inc.php
This is a Work in Progress (WIP).
This adds the validation for domain-names and e-mail addresses via `filter_var()`.
I'm not sure, if `FILTER_VALIDATE_DOMAIN` is available via PHP - the docs don't mention this flag - but it's available in PHP's source code ([here](https://github.com/php/php-src/blob/0437aa2abf1eb494e4555d7d4dfbdbf566a59bdc/ext/filter/logical_filters.c#L509)). I'm investigation this later. 
Mentioned here: #79 #62 
THE CHANGES ARE UNTESTED YET - DO NOT MERGE!
> [WIP] Add correct validation for domain-names/emails

- includes/functions.sh
This fixes issue #66. The /var/www/ directory gets created before copying the htdocs files.
Although I just realised I tested with an oldstable image (7.8). Maybe this error doesn't happen with the stable distribution. But this additional instruction won't hurt anyway.
> Create /var/www/ during installation.

- includes/functions.sh
- postfix/conf/main.cf
- postfix/conf/relay_recipients
- postfix/conf/sql/mysql_virtual_domains_maps.cf
- postfix/conf/sql/mysql_virtual_mxdomain_maps.cf
- postfix/conf/sql/mysql_virtual_mxmailbox_maps.cf
this commit will fix mx backup.
MX backup is currently not working, as "relay_domains" is unset.
- Added mysql query on "relay_domains" for mx domains
- Added a "relay_recipients"-list to setup what addresses are relayed (you may want to implement this in the mailcow gui?!)
- Changed mysql query for final destination domains
> propper mx backup handling

- misc/mc_msg_size
- webserver/apache2/conf/sites-available/mailcow
Hi i've updated mc_size_size to add support for changing upload_max_filesize and post_max_size of apache since the current version doesn't work any more for apache since the config is now  using mod_php instead of php-fpm, i also have to update apache config a bit to be able to change the php setting
> Updated mc_size_size to support apache 

- includes/functions.sh
Current version causes a sed: -e expression #1, char 22: unknown option to `s' error
> Fixed setting date.timezone in apache config

- README.md
- mailcow.config
- roundcube/conf/plugins/managesieve/config.inc.php
- webserver/htdocs/mail/add.php
- webserver/htdocs/mail/admin.php
As described in RFC 2606 and RFC 6761, a number of domains such as example.com and example.org are maintained for documentation purposes.
These domains should be used as illustrative examples in documents as they are not available for registration or transfer.
There is a risk that someone will register domain.tld in  the future.
> Use example.com instead of domain.tld

- webserver/nginx/conf/sites-available/mailcow
In the current configuration nginx only listens to IPv4.
This makes the web interface, CardDAV and CalDAV unusable from Dual Stack or IPv6-only connections.
> Enable IPv6 in nginx

- includes/functions.sh
- spamassassin/conf/local.cf
- spamassassin/conf/local.cf.include
Add a spamassassin/local.cf.include file so that people may add customisations without them being overridden on upgrade.
We have a few system logs that get emailed and keep getting marked as spam which we whitelist in the spamassassin/local.cf file.  This means we don't have to restore them each time we upgrade :-)
> Added a spamassassin/local.cf.include file

- includes/functions.sh
Changing the files names will leave old files on upgraded install and cause clean_spam_aliases corn-job to run twice, not a major issue.
> Mirror fix to commit 387644c

- postfix/conf/main.cf
Fixes #411.
Basically this pull request excludes some weaker and MITM-vulnerable cipher suites and gets rid of a warning that would be shown by SSL-Check due to the usage of those cipher suites.
> Remove weaker cipher suites for secure SMTP

- webserver/htdocs/mail/admin.php
- webserver/htdocs/mail/inc/footer.inc.php
- webserver/htdocs/mail/inc/header.inc.php
Adds SRI for the externally loaded scripts. As recommended by:
https://observatory.mozilla.org
see also:
https://wiki.mozilla.org/Security/Guidelines/Web_Security#Subresource_Integrity
generated with:
https://www.srihash.org/
> add SRI for cloudflare scripts

- webserver/htdocs/mail/inc/header.inc.php
- webserver/nginx/conf/sites-available/mailcow_rc
- webserver/nginx/conf/sites-available/mailcow_sogo
These settings (together with the already merged SRI) lift the [security rating](https://observatory.mozilla.org) from F to A :-)
Getting full points is, to the best of my knowledge, not possible unless no external javascript code is loaded by means of 'unsafe-eval' and 'unsafe-inline'. See also: https://wiki.mozilla.org/Security/Guidelines/Web_Security#Content_Security_Policy
> Increase webserver security by some headers and cookie directive

- includes/functions.sh
- webserver/htdocs/mail/inc/vars.local.inc.php
Hi,
vars.local.inc.php currently get's replaced on upgrades due webserver/htdocs/mail getting copied to /var/www/mail.
All I've done on this mirror commit is deleted webserver/htdocs/mail/inc/vars.local.inc.php and crated vars.local.inc.php if doesn't exist in the webserver install task on functions.sh.
Ryan
> vars.local.inc.php get replaced on upgrade

- webserver/nginx/conf/sites-available/mailcow_sogo
The ssl server block for autodiscover in the nginx SOGo config is missing the root directive.
> Add missing root directive to autodiscover server block (nginx & SOGo)

- webserver/nginx/conf/sites-available/mailcow_rc
The current add_header X-Frame-Options "DENY"; causes Round cube not to work correctly and causing  the loading spin to show all the time.
Chrome error console
Refused to display 'https://mx-de.***.be/rc/skins/larry/watermark.html' in a frame because it set 'X-Frame-Options' to 'DENY'.
app.min.js?s=1477579486:121 Uncaught DOMException: Blocked a frame with origin "https://mx-de.****.be" from accessing a cross-origin frame.(…)
All I've done is changed  X-Frame-Options to SAMEORIGIN and re-added Content-Security-Policy but this time set frame-ancestors to  'self'
This fixes the issue with was caused by a earlier merged Pull Request #523 with the usage of X-Frame-Options "DENY";
> Fixed add_header rc

- webserver/htdocs/mail/js/mailbox.js
This pull request fixes a bug in the javascript code that contains the filtering algorithm of the mailbox page. This fixes the deletion of all table row in all panels that has the class of "filterTable_no_results" whenever any filter text input field was modified. Hence we should expect that editing the filter text input field of a panel should not affect other panels.
> This bug also exists in mailcow 0.14 final and probably in older versions of mailcow. This isn't a major issue though.
Bug demo:
[![DEMO](https://img.youtube.com/vi/n3dwr_b9W4U/0.jpg)](https://www.youtube.com/watch?v=n3dwr_b9W4U)
> Mailcow Filter Bug

- webserver/htdocs/mail/admin.php
- webserver/htdocs/mail/mailbox.php
- webserver/htdocs/mail/user.php
This PR fixes some dislocation of "::after" pseudo element in the tables on devices with small screen like mobile phones.
> Aligned table column headers

- webserver/htdocs/mail/inc/header.inc.php
- webserver/htdocs/mail/inc/prerequisites.inc.php
- webserver/htdocs/mail/index.php
This fix makes switching to new language more convenient by utilizing GET query, instead of POST.
**This means:**
* Users can switch language by opening "https://[mail.example.com]/?lang=**en**", where **en** can be **pt** or **de**.
* Every language switching activity will be cached in the cookie for future use.
* Logging out will not reset the language to default.
* Language will not change in the cookie unless you explicitly switched language via mailcow web ui.
* Switching to another language while in a page with get query works well.
> Language Switching is improved

- webserver/htdocs/mail/add.php
- webserver/htdocs/mail/admin.php
- webserver/htdocs/mail/delete.php
- webserver/htdocs/mail/edit.php
- webserver/htdocs/mail/index.php
- webserver/htdocs/mail/mailbox.php
- webserver/htdocs/mail/user.php
If PHP scripts are not exited after declaring a location header, execution will continue. This is for security and performance purposes.
> Terminate of Script After Redirect Directive

- includes/functions.sh
- webserver/htdocs/mail/inc/functions.inc.php
The hardcoded template for the anonymizer headers in functions.inc.php
didnt match the default file in postfix/conf/. This fixes this problem by creating a template and loading
the contents of this file to write to the config file.
> Uses template to set anonymize headers

- includes/functions.sh
When successfully acquiring a Let's Encrypt certificate we leave the user with wrong certificates in Dovecot and Postfix.
Added both services in `ssl-le` to be restarted. A "cleaner" approach could be to restructure [install.sh](https://github.com/andryyy/mailcow/blob/master/install.sh) and move L138 - L141 in front of restarting all services.
Edit: Spelling.
> LE: Restart Postfix and Dovecot

- webserver/htdocs/sogo.sql
(may be local effect with a quite fresh install)
sogo.sql breaks during install/upgrade process.
> avoid upgrade problems if alias domains are already created.

- includes/functions.sh
Current functions.sh doesn't adapt the database connection settings to the user variables during installation.
> Added missing adaptation of fuglu.conf
