mailcow/mailcow

webserver/htdocs/mail/inc/functions.inc.php
Without this commit the following php error appears:
Fatal error: Can't use function return value in write context line 838
Fixes issue #83
=> Fixes return value in write context error.

webserver/nginx/conf/sites-available/mailcow
This PR is a part of #149 
This PR is associated with #140
=> #140 Make Webserver less talky

webserver/htdocs/mail/inc/footer.inc.php, webserver/htdocs/mail/inc/header.inc.php
https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.7.5
=> bootstrap-select version bump 1.7.5 / Remove javascript sourcemaps

includes/functions.sh, webserver/apache2/conf/sites-available/mailcow.conf
Better SSL security settings. You'll get an A+ rating when testing your domain on https://www.ssllabs.com.
Requires enabled Apache-mod "headers"
=> Increase SSL security

dovecot/conf/dovecot.conf, postfix/conf/main.cf
=> Update dovecot and postfix to listen to IPv6.

includes/functions.sh
I think that it's related to commit 6e6dac5be5c6cb4583679549af6ae08f3964b59a.
=> Fix a regression introduced in latest commit

includes/functions.sh
This is a much nicer way to modify sudoers.
For more info on that read `/etc/sudoers.d/README`.
=> use /etc/sudoers.d/ instead of /etc/sudoers

README.md, includes/functions.sh, install.sh, mailcow.config, webserver/htdocs/init.sql
I was unable to run it on Ubuntu 16.04 and decided to give it a try.
While doing this, I also included a possibility to speed up test runs. I believe that having the names of the tasks only improves maintainability (adding future tasks).
=> Support Ubuntu 16.04

webserver/htdocs/mail/inc/header.inc.php
=> Removes margin in the progress bar of quota

webserver/htdocs/mail/add.php, webserver/htdocs/mail/admin.php, webserver/htdocs/mail/delete.php, webserver/htdocs/mail/edit.php, webserver/htdocs/mail/inc/footer.inc.php, webserver/htdocs/mail/mailbox.php, webserver/htdocs/mail/user.php
This pull request in regard of the known [XSS Vulnerability](https://github.com/andryyy/mailcow/issues/583) of Mailcow. I've tested this modification and I can say that it results no errors (on my side). However, please test this yourself for verification. **I also encourage you to review the changes that I've made, for you might have better implementations than mine**. 😄 
> **This is a partial fix of the said issue**. More pull requests or file modifications will be made soon after my tests has been done.
=> Input Sanitation - XSS Prevention

webserver/htdocs/mail/inc/functions.inc.php, webserver/htdocs/mail/lang/lang.de.php, webserver/htdocs/mail/lang/lang.en.php, webserver/htdocs/mail/lang/lang.pt.php
Hi @andryyy/ @admf ,
I think you missed to add language strings with these files.
I have added new strings that require translation in Deutsch and Portuguese.
=> Added missing language strings

README.md
Please check if the requirements are correct and add the missing values.
=> Add System Requirements

postfix/conf/mailcow_anonymize_headers.pcre, postfix/conf/main.cf, postfix/conf/master.cf
reverts main.cf/master.cf back to 67e60f2c241aaef1f87af26867cebc9aa887c50b-1
Minor indent fix main.cf
replaces regex
=> Fix anonymizer-function headers

webserver/htdocs/mail/inc/prerequisites.inc.php
Makes the language permanent for a computer even if the session is expired.
=> Added 3 month expiration to language settings

webserver/htdocs/mail/admin.php, webserver/htdocs/mail/inc/functions.inc.php
Added in the admin panel a graph to show cpu usage
=> Added CPU Usage Info

webserver/htdocs/mail/admin.php, webserver/htdocs/mail/inc/functions.inc.php
we can work into the design later.
=> Added system uptime

webserver/htdocs/mail/admin.php
this PR contains:
* Minor PR enhancement
* Added Uptime info
* Added hostname info
* Added mailcow version info
=> Sysntem Info enhancement

webserver/htdocs/mail/admin.php
Hi,
I know most of the system info reports will be removed in favor of the dockerized version, but let us see what time brings us. Maybe we can find another php function that is compatible with the dockerized version and retain the required infos.
=> System info improved

README.md, includes/functions.sh
=> Updated FuGlu dependencies

README.md
=> Update README.md on DNS records and SPF/DKIM

README.md
Project is outdated, written in bold.
Should warn users and avoid issue like #898.
=> Add a note
